In [1]:
import numpy as np

In [2]:
#CREATING NUMPY ARRAY

In [3]:
dimz_list = [1,2,3,4,5,6,7]#This is a list

In [8]:
np.array(dimz_list)
#click shift-tab on array to find out more about the array function
#put in an object in the array, to work with, its parameters

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
x = np.array(dimz_list)
#assign the array as a variable x

In [10]:
type(x)
#check the type of x

numpy.ndarray

In [11]:
dimz_matrix = [[1,2,3],[4,5,6],[7,8,9]]
#Nested list is a list of a list

In [12]:
np.array(dimz_matrix)
#turns the nested list to a matrix format of 3 by 3
#Numpy is smart enough to realize its 3 dimensional matrix n arrange it
#The 2 sets of square brackets at the beginning and end notates that its 2 dimensional, 3 brackets is 3 dimensional n so on

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
list(range(1,7))
#Built in range function for python

[1, 2, 3, 4, 5, 6]

In [15]:
np.arange(1,7)
#numpys version for range
#prints as an array in brackets

array([1, 2, 3, 4, 5, 6])

In [16]:
np.arange(0,27,3)
#You can also use the range parameters:start,end,step
#starting point, last but not inclusive and difference btw each number

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [18]:
#Generating arrays for zeros n ones is useful for financial models 
np.zeros(3)
#This returns an array or matrix of zeros, 3 zeros
#pandas auto changes the number type to float instead of integer so we dont lose any decimal data

array([0., 0., 0.])

In [19]:
np.zeros((3,5))
#A tuple of zeros matrix
#3 rows and 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((3,4))
#same as zeros

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(0,10,30)
#linspace is like range but gives back evenly spaced numbers btw the start n stop
#It takes in 3 parameters:start,stop and the amount of numbers you want inbtw to be evenly spaced

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [22]:
np.linspace(2,6,1)

array([2.])

In [23]:
np.linspace(2,8,1)

array([2.])

In [24]:
np.linspace(2,6,3)

array([2., 4., 6.])

In [25]:
np.linspace(2,8,3)

array([2., 5., 8.])

In [26]:
np.linspace(2,6)
#if no amount of numbers you want inputted then default is 50 numbers

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [28]:
np.eye(5)
#Identity matrix is an even matrix so it takes in just one parameter
#The one parameter is the rows n also the columns
#It prints out zeros with only the diagonals as ones

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
#There are a lot of methods n distributions used to create random numbers on numpy
np.random.rand(6)
#np.random. then press tab to see the different list of methods you can use to print random numbers
#.rand means pick a number randomly btw 0 and 1, any no can be chosen, uniform distribution(every no has the same odds of being picked)
#The parameter 6 means that you want only 6 numbers randomly chosen

array([0.03435419, 0.5251819 , 0.49141301, 0.21078482, 0.97881723,
       0.98676527])

In [32]:
np.random.rand(3,4)
#Means give me a 3 by 4 matrix with random nos btw 0 and 1

array([[0.11410037, 0.67938495, 0.4591535 , 0.31885205],
       [0.03543711, 0.47945329, 0.33053508, 0.4760726 ],
       [0.89459342, 0.08226065, 0.50745687, 0.02694098]])

In [34]:
np.random.randn(6)
#.randn means from a standard "normal" (gaussian) distribution(the odds of being chosen are not the same)
#The closer you are to zero the higher the probabilities of being chosen, so mean is 0 and variance is 1, negatives are involved too

array([ 0.01340044,  1.09261602,  1.70425569, -1.35145322,  0.17009997,
        1.17281176])

In [35]:
np.random.randn(3,4)

array([[ 1.02957465,  0.17955019, -0.26835526,  1.39646597],
       [ 0.21735307, -0.36455679, -2.29433761, -0.19951527],
       [ 0.22278557, -0.45517427, -0.52347316,  1.26544646]])

In [38]:
np.random.randint(1,50)
#Random no for integers
#start,stop n amount, stop is not inclusive, default for amount is just 1

45

In [42]:
np.random.randint(1,50,6)

array([44, 46, 15, 31, 11, 12])

In [58]:
dim_arr = np.arange(8)
dim_ranarr = np.random.randint(1,50,6)

In [59]:
dim_arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [45]:
dim_ranarr

array([40, 12, 43, 35, 47, 28])

In [61]:
dim_arr.reshape(2,4)
#.reshape, reshapes the array into the form you want
#If you're reshaping into matrix then it has to be divisible or else it will give an error
#It has to be exactly multiplied like the two matrix nos multiplied together would give you the range number

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [62]:
dim_arr.reshape(4,2)
np.arange(1,26).reshape(10,10)#This prints out your result then reshapes it to any form you want, matrix maybe

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [55]:
dim_arr.shape
#Displays that it's a one dimensional shape, 24,nothing

(24,)

In [63]:
dim_arr.reshape(4,2).shape
#Its a two dimensional now

(4, 2)

In [64]:
dim_arr.reshape(8,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [65]:
dim_arr.reshape(8,1).shape

(8, 1)

In [67]:
dim_arr.dtype
#If you want to know the data type the array is holding, just use dtype
#This is an integer of 32 bits

dtype('int32')

In [68]:
dim_ranarr

array([38, 29,  8,  5, 17, 24])

In [69]:
dim_ranarr.max

<function ndarray.max>

In [70]:
dim_ranarr.max()
#To recieve the max number in the random array

38

In [71]:
dim_ranarr.argmax()
#The index position of the max number, counting always starts from 0

0

In [72]:
dim_ranarr.min()

5