In [4]:
#methods come with brackets at the end()  while attributes have just .whatever without the brackets at the end
import numpy as np

In [5]:
dim = np.arange(0,10)

In [3]:
dim

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
dim + dim
#it adds each array one by one, index 1 plus index 1 n so on

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
dim * dim

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
dim/dim
#Zero divived by zero(0/0) is a non applicable value,doesnt make sense

<ipython-input-7-6bd6d5cc868f>:1: RuntimeWarning: invalid value encountered in true_divide
  dim/dim


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
1/dim
#One divided by 0(1/0) is infinity

<ipython-input-8-eb2147544731>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/dim


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [9]:
dim ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [10]:
dim + 50

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [11]:
np.sqrt(dim)
#Takes the square of everything in the array
#np.tab displays a list of mostly operations with numpy

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [12]:
np.exp(dim)
#Exponential of the array

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [13]:
np.max(dim)

9

In [15]:
dim.max()
#This just takes the max func of np, same output as above

9

In [16]:
np.sin(dim)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [18]:
dim.sin()
#Doesnt work for all the operations

AttributeError: 'numpy.ndarray' object has no attribute 'sin'

In [19]:
np.log(dim)

<ipython-input-19-b394cc6179e8>:1: RuntimeWarning: divide by zero encountered in log
  np.log(dim)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [20]:
dim[7]
#This will print value at index count 7

7

In [21]:
dim[4:8]
#Gives values index 4 to 8, 2 parameters,start n stop(not inclusive)

array([4, 5, 6, 7])

In [22]:
dim[:5]
#Just stop pm so beginning to index 5

array([0, 1, 2, 3, 4])

In [24]:
dim[3:]
#Starting position till the end

array([3, 4, 5, 6, 7, 8, 9])

In [6]:
#Broadcasting is a main difference btw python numpy array n python list
dim[0:5] = 50
dim
#The list cannot change this index 0 to 5 to a specific number only
#This is broadcasting

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9])

In [7]:
dim = np.arange(0,10)

In [8]:
dim

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
slice_of_dim = dim[0:5]
#Slice of the array you want to change is from index 0 to index 5

In [14]:
slice_of_dim
#Slice of the array name is a piece of the array you want to change separately

array([0, 1, 2, 3, 4])

In [20]:
slice_of_dim[:] = 12
#Changes everything in the slice of the array to 12

In [18]:
slice_of_dim
#Slice of the array print out

array([12, 12, 12, 12, 12])

In [19]:
dim
#The slice changes the original array

array([12, 12, 12, 12, 12,  5,  6,  7,  8,  9])

In [21]:
dim_copy = dim.copy()
#This explicitly makes a copy of the array so you can work with it differently

In [22]:
dim_copy[:] = 11

In [23]:
dim_copy
#This is a copy of the dim array that you changed

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [24]:
dim

array([12, 12, 12, 12, 12,  5,  6,  7,  8,  9])

In [31]:
dim = np.array([[5,6,7],[8,9,10],[11,12,13]])

In [32]:
dim

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [33]:
#If you want to get a specific row or column or a specific number, just use
#dim[row,column]
#dim[row][column]

In [34]:
dim[2]

array([11, 12, 13])

In [35]:
dim[1,2]

10

In [36]:
dim[1][2]

10

In [40]:
dim[:2,1:]
#If i want to grab just 6,7,9,10. everything but the last row then everything but the first column
#start:stop(not inclusive) for both row n column

array([[ 6,  7],
       [ 9, 10]])

In [47]:
dim[1:2,0:1]

array([[8]])

In [48]:
dim[1:,:2]
#the stop is not inclusive, ALWAYS REMEMBER

array([[ 8,  9],
       [11, 12]])

In [49]:
#Conditional Selection

In [50]:
dim = np.arange(1,11)

In [51]:
dim

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
dim > 4
#We want to see if the values in the array are greater than 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [56]:
bool_dim = dim > 4
#got the results from the greater than 4 and saved as a bool array

In [57]:
dim[bool_dim]
#Then when we pass the boolean array into the original array, we get only the TRUE values

array([ 5,  6,  7,  8,  9, 10])

In [59]:
#Turn the 3 steps into a short one of just one step
dim[dim > 4]

array([ 5,  6,  7,  8,  9, 10])

In [60]:
dim[dim <= 5]

array([1, 2, 3, 4, 5])